function [BW_out,properties] = filterRegions(BW_in)
%filterRegions  Filter BW image using auto-generated code from imageRegionAnalyzer app.
%  [BW_OUT,PROPERTIES] = filterRegions(BW_IN) filters binary image BW_IN
%  using auto-generated code from the imageRegionAnalyzer App. BW_OUT has
%  had all of the options and filtering selections that were specified in
%  imageRegionAnalyzer applied to it. The PROPERTIES structure contains the
%  attributes of BW_out that were visible in the App.

% Auto-generated by imageRegionAnalyzer app on 25-Sep-2019
%---------------------------------------------------------

BW_out = BW_in;
% Filter image based on image properties.
[f_in,c_in]=size(BW_in);
if ((f_in>1000 && c_in>1000))
    BW_out = bwpropfilt(BW_out, 'Area', [300000, 1000000]);
else
    BW_out = bwpropfilt(BW_out, 'Area', [300, 1000000]); %descomentar si uso la biblioteca de imagenes
end
% Get properties.
properties = regionprops(BW_out, {'Area', 'Eccentricity', 'EquivDiameter', 'EulerNumber', 'MajorAxisLength', 'MinorAxisLength', 'Orientation', 'Perimeter'});

end
